spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 10
      pool-name: CloudHikari
    username: root
    password: 0c5babd935745275
    url: jdbc:mysql://127.0.0.1:3306/medical_appointment?useUnicode=true&characterencoding=utf-8&useSSL=true&serverTimezone=UTC
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: ASSiGN_ID
mybatis:
  mapper-locations: classpath*:mapper/*.xml  # XML 映射文件路径
  type-aliases-package: com.base.framework.admin.entity
  configuration:
    map-underscore-to-camel-case: true
